2016-11-18 11:22:53,162 - 59 - INFO - log file:/data/BI/vdw/log/buff/buff.dw_user/20161118/signal_table_extract_handler.py_20161118112253.log
2016-11-18 11:22:53,163 - 60 - INFO - /data/BI/vdw/bat/signal_table_extract_handler.py buff.dw_user
2016-11-18 11:22:53,163 - 61 - INFO - ex_sql_file:/data/BI/vdw/sql/buff/buff.dw_user.sel.sql
2016-11-18 11:22:53,163 - 62 - INFO - tmp_ex_sql_file:/data/BI/vdw/tmp/buff/buff.dw_user.sel.sql20161118112253
2016-11-18 11:22:53,163 - 63 - INFO - UOW:20161115000000,20161116000000
2016-11-18 11:22:53,163 - 64 - INFO - ex_data_folder:/data/BI/vdw/in/buff/buff.dw_user/20161116000000
2016-11-18 11:22:53,163 - 65 - INFO - ex_data_file:/data/BI/vdw/in/buff/buff.dw_user/20161116000000/buff.dw_user.dat
2016-11-18 11:22:53,163 - 92 - INFO - command: psql -h 172.16.4.138 -p 5432 -d vliveshow -v ON_ERROR_STOP=1 -U bi_con -f /data/BI/vdw/tmp/buff/buff.dw_user.sel.sql20161118112253
2016-11-18 11:22:53,164 - 93 - INFO - {'{UOW_FROM}': '20161115000000', '{ETL_ID}': 'buff.dw_user', '{LEVEL_ID}': 'buff', '{TABLE_ID}': 'dw_user', '{UOW_TO}': '20161116000000'}
2016-11-18 11:22:53,172 - 109 - INFO - psql:/data/BI/vdw/tmp/buff/buff.dw_user.sel.sql20161118112253:1: ERROR:  relation "publi.user" does not exist
2016-11-18 11:22:53,172 - 109 - INFO - LINE 1: ...lowing, follower, phone_encrypt , is_blocked from publi. "us...
2016-11-18 11:22:53,172 - 109 - INFO - ^
2016-11-18 11:22:53,172 - 115 - INFO - extract_record:0
2016-11-18 11:22:53,172 - 118 - ERROR - extract executed false.
